name: Deploy application to ec2
on:
  push:
    branches:
      - "main"

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            ls && cd deploy-to-ec2
            cd backend && npm ci && npm run build
            cd ../frontend && npm ci && npm run build
            pm2 restart backend-server && pm2 restart frontend-server
